### PR TITLE
Rework paging

### PR DESCRIPTION
**Pull request by mkroening**

### CODE REVIEW

**Review by stlankes — APPROVED** [review]
bors r+

**Comment by mkroening** [comment]
I'll look into the uhyve failure tomorrow.

**Comment by mkroening** [comment]
This was the problem: https://github.com/hermitcore/libhermit-rs/blob/d76bb784af0d864ceebab6c73ab2c322073f8594/src/arch/x86_64/mm/paging.rs#L242-L246

bors r=stlankes

**Comment by mkroening** [comment]
The failure was spurious.

bors retry

**Comment by mkroening** [comment]
bors retry

**Pull request merged**
