### PR TITLE
CI: Don't test microvm

### PR DESCRIPTION
**Pull request by mkroening**
This disables running microvm in CI for now until https://github.com/hermitcore/libhermit-rs/issues/161#issuecomment-1006022190 is fixed.

### CODE REVIEW

**Comment by mkroening** [comment]
I added this commit to https://github.com/hermitcore/libhermit-rs/pull/327, since we need both PRs for a passing CI.

**Comment by mkroening** [comment]
Reopened hoping we can merge this being lucky with GitLab CI until https://github.com/hermitcore/libhermit-rs/pull/327 is solved properly.

**Comment by mkroening** [comment]
Nevermind, I made a mistake in #327.

**Comment by mkroening** [comment]
Not making the same mistake again, it seems like merging this should be possible though, if we are lucky.

**Comment by mkroening** [comment]
@stlankes, are you okay with disabling microvm CI?

**Comment by stlankes** [comment]
I would not remove the microVM tests. PR #335 is a workaround for this issue.

With KVM acceleration, the microVM is able to determine the frequency. By emulation, we pass the frequency with the Qemu flag `-append "-freq XXX"`. However, the loader is currently not able to pass the command line to our kernel. I looked into the code. I don't see any failure in our implementation or in the crate `multiboot`. The latest Qemu version for Ubuntu could have an issue. We have to investigate it.

**Comment by mkroening** [comment]
All right. :ok_hand: 
Closing in favor of #335.

**Pull request closed without merging**
