### PR TITLE
Moved pipeline to new gitlab CI runners

### PR DESCRIPTION
**Pull request by jounathaen**

### CODE REVIEW

**Comment by jounathaen** [comment]
It looks like the reason for the fails is the code and not the infrastructure anymore :slightly_smiling_face::+1:

**Comment by stlankes** [comment]
No :-)

We need the privileged runner to test the kernel with KVM. We have currently a problem with the release version, which is reason that "user-space" isn't able to run.

**Comment by jounathaen** [comment]
The gitlab runner should actually have KVM access. I have to check again...

**Comment by stlankes** [comment]
Unfortunately I have closed the PR by mistake. However, your changes are already integrated in the latest version.

**Pull request closed without merging**
