### PR TITLE
Replace pci_ids.rs with pci-ids crate

### PR DESCRIPTION
**Pull request by mkroening**
pci-ids also uses phf, which should be faster than iterating all ids.

I added support for `no_std` [1] as well as classes [2] to the pci-ids crate.

[1]: https://github.com/lienching/pci-ids.rs/pull/3
[2]: https://github.com/lienching/pci-ids.rs/pull/11

### CODE REVIEW

**Comment by mkroening** [comment]
This depends on https://github.com/lienching/pci-ids.rs/pull/3.

**Review by stlankes — APPROVED** [review]
bors r+

**Comment by stlankes** [comment]
bors retry

**Pull request merged**
