### PR TITLE
[Revert] Disable Windows CI for now

### PR DESCRIPTION
**Pull request by mkroening**
Something is wrong with QEMU: https://github.com/hermitcore/libhermit-rs/runs/6109029660

### CODE REVIEW

**Review by stlankes — APPROVED** [review]
bors r+

**Comment by stlankes** [comment]
Do you have any idea, where the issue comes from?

**Comment by stlankes** [comment]
I am confused. On our systems bors runs successfully. @mkroening Any idea for the timeout?

**Comment by stlankes** [comment]
bors retry

**Comment by stlankes** [comment]
bors retry

**Comment by mkroening** [comment]
Ah, I forgot to remove the Windows CI requirement from the borsfile, so bors waited for the disabled job.

bors r=stlankes

**Pull request merged**
