### PR TITLE
Add xtask crate for kernel building

### PR DESCRIPTION
**Pull request by mkroening**
Closes https://github.com/hermitcore/rusty-hermit/issues/188.

This adds an xtask package, with two subcommands `build` and `clippy`.
`build` builds the kernel with the correct arguments and does any necessary post processing (symbol renaming).
`clippy` runs clippy on the kernel for multiple architectures (though only `x86_64` at this time - see https://github.com/hermitcore/libhermit-rs/issues/381).

### CODE REVIEW

**Comment by stlankes** [comment]
@mkroening Can you check, if I merged everything correctly.

**Comment by mkroening** [comment]
I rebased and adjusted for https://github.com/hermitcore/libhermit-rs/pull/395. Now it is ready to merge, if you don't have any objections.

**Comment by mkroening** [comment]
bors r=stlankes

**Comment by mkroening** [comment]
bors r=stlankes

**Comment by mkroening** [comment]
bors r=stlankes

**Comment by mkroening** [comment]
bors r=stlankes

**Comment by mkroening** [comment]
bors retry

**Comment by stlankes** [comment]
bors try

**Comment by mkroening** [comment]
I'll have to do some adjustments to GitLab CI, which I did not test before.

**Comment by stlankes** [comment]
@mkroening I think that our CI container isn't starting

**Comment by stlankes** [comment]
bors try

**Comment by mkroening** [comment]
bors r=stlankes

**Comment by mkroening** [comment]
bors cancel

**Comment by mkroening** [comment]
bors cancel

**Comment by mkroening** [comment]
bors try

**Comment by mkroening** [comment]
bors try

**Comment by stlankes** [comment]
bors try

**Comment by mkroening** [comment]
bors r=stlankes

**Comment by mkroening** [comment]
bors retry

**Pull request merged**
