### PR TITLE
SMP Boot Code: Include via include_nasm_bin!

### PR DESCRIPTION
**Pull request by mkroening**
This addresses smp_boot_code.rs in https://github.com/hermitcore/libhermit-rs/issues/333.

I published a crate for assembling and including binaries via NASM at compile time: [include-transformed](https://crates.io/crates/include-transformed).

### CODE REVIEW

**Comment by stlankes** [comment]
CMake is required for hermit-playground. The C user land use CMake as build system.

**Comment by mkroening** [comment]
Yeah, but the Rust project depends on CMake for two files as explained in https://github.com/hermitcore/libhermit-rs/issues/333.

I'm removing the CMake dependency for the rust project. I'm not trying to remove CMake scripts for hermit-playground.

**Comment by stlankes** [comment]
Ah, you are right!

**Comment by mkroening** [comment]
bors try

**Comment by mkroening** [comment]
bors try-

**Comment by mkroening** [comment]
bors try

**Review by stlankes — APPROVED** [review]
bors r+

**Comment by mkroening** [comment]
bors retry

**Comment by mkroening** [comment]
bors retry

**Comment by mkroening** [comment]
bors retry

**Pull request merged**
