### PR TITLE
Rename .cargo/config to config.toml

### PR DESCRIPTION
**Pull request by mkroening**

### CODE REVIEW

**Comment by mkroening** [comment]
The clippy failure has nothing to do with this PR but is introduced by better lints in newer nightlies. #216 addresses this by making sure to use the nightly specified in `toolchain.toml`.

**Comment by stlankes** [comment]
@mkroening Clippy doesn't like the renaming of the toolchain file. Do you know a solution?

**Comment by mkroening** [comment]
Rebased on latest `master`.

**Review by stlankes — APPROVED** [review]
bors r+

**Pull request merged**
