### PR TITLE
using write_volatile to guarantee that the data is written to the I/O device

### PR DESCRIPTION
**Pull request by stlankes**
@simonschoening reports that the current implementation doesn't work on RISC-V. By using `write_volatile` we should get a more platform independent solution.

### CODE REVIEW

**Comment by mkroening** [comment]
Ah, yes. This partly fixes https://github.com/hermitcore/libhermit-rs/issues/199.

The problem is known since May, when we disabled `mutable-noalias` as a workaround.

I am still waiting on https://github.com/rust-osdev/volatile/pull/22 to do an rework on all affected drivers.

In the meantime, this is a good step in the right direction. :+1: 

bors r+

**Review by mkroening — APPROVED** [review]

**Comment by mkroening** [comment]
bors retry

**Comment by stlankes** [comment]
bors retry

**Pull request merged**
