### PR TITLE
use write_unaligned to write data to the pci device

### PR DESCRIPTION
**Pull request by stlankes**
gurantees that the kernel 16-/32-bit registers to write the data to the device memory

### CODE REVIEW

**Review by mkroening — CHANGES_REQUESTED** [review]
I think, we might even have to use [`core::intrinsics::unaligned_volatile_store`](https://doc.rust-lang.org/nightly/core/intrinsics/fn.unaligned_volatile_store.html) here.

**Comment by stlankes** [comment]
In this case, we have to enable the nightly feature _core_intrinsics_. Do we want it?

**Comment by mkroening** [comment]
> In this case, we have to enable the nightly feature _core_intrinsics_. Do we want it?

We'd rather not, but I am uncertain if using inline assembly to emulate the intrinsic would be better. Maybe we should go for `core_intrinsics`. 🤔

**Comment by stlankes** [comment]
Ok, I enabled the feature

**Review by mkroening — APPROVED** [review]

**Pull request merged**
