### PR TITLE
Rework Dockerfile

### PR DESCRIPTION
**Pull request by mkroening**
This rewrites the Dockerfile and moves all dependencies into the docker image, where dependencies are compiled modularly on their respective toolchains.

Note that this moves the base image from `ubuntu:latest` to `debian:bullseye`.

### CODE REVIEW

**Comment by mkroening** [comment]
bors try

**Comment by mkroening** [comment]
bors try

**Comment by mkroening** [comment]
bors try

**Comment by mkroening** [comment]
bors try

**Comment by mkroening** [comment]
bors try

**Review by stlankes — APPROVED** [review]

**Pull request merged**
