### PR TITLE
clearify license text, add workround to use raw-cpuid

### PR DESCRIPTION
**Pull request by stlankes**
The workaround should solve issue hermitcore/libhermit-rs#164 and is only necessry until gz/rust-x86#71 is accepted.

### CODE REVIEW

**Comment by jbreitbart** [comment]
Why do we need that workaround? Just to close #164 ? Is it really worth it or should we just wait until @gz makes a new release of the x86 crate?

**Comment by stlankes** [comment]
You are right, the crate will come. We are able to wait

**Comment by gz** [comment]
Released 0.36, Thanks!

**Comment by stlankes** [comment]
@gz I didn't want to put any pressure on you. Thanks for the fast response.

**Pull request merged**
