### PR TITLE
fix bug by building the minimal version of libhermit

### PR DESCRIPTION
**Pull request by stlankes**
This PR should solve issue #157 In addition, I add a small test to build the minimal configuration.

### CODE REVIEW

**Comment by stlankes** [comment]
@jschwe It seems to work...

**Comment by jschwe** [comment]
@stlankes Have you tried building and running an application? 
I get a lot of GP Exceptions when trying to run hello-world with no-default-features and this PR, but maybe I'm doing something wrong.
Steps:
1. Checkout master of rusty-hermit
2. Checkout this PR  into libhermit-rs
3. go back to rusty-hermit directory
4. ` cargo build --manifest-path examples/hello_world/Cargo.toml --target x86_64-unknown-hermit --no-default-features`
5. `cd loader && make && cd ..`
6. `qemu-system-x86_64 -display none -smp 1 -m 64M -serial stdio  -kernel loader/target/x86_64-unknown-hermit-loader/debug/rusty-loader -initrd target/x86_64-unknown-hermit/debug/pi_sequential -cpu qemu64,apic,fsgsbase,rdtscp,xsave,fxsr`

**Comment by stlankes** [comment]
It works only on uhyve, QEMU depends on PCI.... That is the reason, why I don't test it within GitHub Actions. In the future, I want to support of Qemu's Micro VM (https://github.com/bonzini/qemu/blob/master/docs/microvm.rst). Currently, it doesn't run on it. I have to check, why it isn't working on this setup.

**Comment by jschwe** [comment]
Ah okay, that explains it. 
I suggest to build the minimal kernel with `--target x86_64-unknown-hermit-kernel` and remove the `std` from `-Z build-std=<>`.
In practice, it's not really relevant of course, since we aren't using the binary, but I think it's better to stay consistent regarding the different parameters when building the kernel vs an application.
Other than that the PR looks good.

**Comment by stlankes** [comment]
You are right, I fixed it

**Review by jschwe — APPROVED** [review]

**Comment by stlankes** [comment]
bors retry

**Comment by jschwe** [comment]
It appears that both the integration tests and the multithreaded uhyve test is failing. The multithreaded uhyve tests crashes, but still seems to exit with 0, which causes the test to appear as passed, even though it should have failed. I'll open an issue over at uhyve to track this.
The integration tests seem to be running fine, but uhyve (or possibly also libhermit) doesn't exit after they are finished. 


I also noticed, that the way I'm dumping the stdout in the integration tests does not really result in very readable output, so I'll open a PR to improve that in the next days.

**Pull request merged**
