### PR TITLE
Ran `cargo fmt`

### PR DESCRIPTION
**Pull request by jbreitbart**
Is there any specific reason the code is manually formatted :smile:

### CODE REVIEW

**Comment by stlankes** [comment]
I likes tabs :-)

**Comment by jbreitbart** [comment]
> Gofmt's style is no one's favorite, yet gofmt is everyone's favorite.

:stuck_out_tongue_closed_eyes:

But feel free to set your own config https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

**Comment by stlankes** [comment]
You are right. I will check it.

**Comment by stlankes** [comment]
I added a config... See commit 08b64b1

**Pull request closed without merging**
