### PR TITLE
Rework C string abstractions

### PR DESCRIPTION
**Pull request by mkroening**

### CODE REVIEW

**Comment by stlankes** [comment]
Naive question. What is the benefit of your implementation?

**Comment by mkroening** [comment]
I didn't like the c_str functions in util very much. Thus I adapted the `CStr` from std abstraction to replace them.

This resolves the `TODO`s on the original functions and avoids unnecessary allocations.

**Comment by mkroening** [comment]
bors retry

**Comment by mkroening** [comment]
bors retry

**Pull request merged**
