### PR TITLE
add support of processors, which doesn't support FSGSBASE

### PR DESCRIPTION
**Pull request by stlankes**
by detecting the FSGSBASE support, the dispatcher will be patched to support it

### CODE REVIEW

**Review by jbreitbart — COMMENTED** [review]
I hate to be that guy, but I am not sure if we really need support for CPUs without FSGSBASE. Intel added support with Ivy Bridge (2005) and AMD has support in their whole Zen lineup.

I am worried that this just adds complexity without any real benefit. There is no bug in a feature that is not available. Sorry. :roll_eyes:

**Comment by jschwe** [comment]
@jbreitbart FYI Ivy bridge was launched in 2012 and AMD Zen in 2017. 

Of course, your argument about the added complexity still stands.

**Comment by jbreitbart** [comment]
> @jbreitbart FYI Ivy bridge was launched in 2012 and AMD Zen in 2017.

Thanks, that is true. I originally wanted to write CPUs older than 5 years, but decided to check the release date of Ivy Bridge and than my mind somehow decided to fuse the infos to 2005. 🤦

**Comment by stlankes** [comment]
I totally agree, but our internal CI consists of old cluster. To test the kernel with uhyve (which depends on nested virtualization), we need such a patch.

**Pull request merged**
