### PR TITLE
Install latest published version from crates.io

### PR DESCRIPTION
**Pull request by stlankes**

### CODE REVIEW

**Comment by mkroening** [comment]
I already added this to https://github.com/hermitcore/libhermit-rs/pull/271

**Comment by mkroening** [comment]
You also missed a line from https://github.com/hermitcore/libhermit-rs/pull/271/commits/1487618a682e768b9a5536488ae3e0284ccb827c

**Comment by mkroening** [comment]
Closing this in favor of https://github.com/hermitcore/libhermit-rs/pull/271

bors r-

**Comment by stlankes** [comment]
Ok, I understand

**Pull request closed without merging**
