### PR TITLE
port libhermit to support C-based applications

### PR DESCRIPTION
**Pull request by stlankes**
- using of VirtAddr also for newlib-based applications

### CODE REVIEW

**Review by tlambertz — APPROVED** [review]
I don't use cmake to build my applications, so I can't check the validity of all changes. The x86 hermit-kernel json target file should not be needed anymore, since the target is contained in upstream rustc?

The other changes are identical to mine and work.

**Comment by stlankes** [comment]
Yes, maybe the changes aren't important. In the json-files, I define that we use a GNU linker. In case of Rust, we use `rust-ldd`. Maybe they're no differences between the linkers.

**Comment by stlankes** [comment]
bors try

**Comment by stlankes** [comment]
bors try

**Pull request merged**
